FROM node:18

WORKDIR /app

COPY package-lock.json ./
COPY packages/example/package.json ./

RUN npm i

COPY packages/example/pb ./pb
COPY packages/example/server.ts ./

CMD ["npm", "run", "dev:server"]