version: '3'

services:
  envoy:
    container_name: envoy
    build:
      context: ./packages/example/envoy/
    ports:
      - '4000:4000'

  server:
    container_name: server
    build:
      dockerfile: Dockerfile.server
    ports: 
      - '1234:1234'