// @generated by protobuf-ts 2.9.0 with parameter server_grpc1
// @generated from protobuf file "example.proto" (syntax proto3)
// tslint:disable
import { Address } from "./example_dep";
import { GetUserAddressRequest } from "./example";
import { CreateUserResponse } from "./example";
import { CreateUserRequest } from "./example";
import { User } from "./example";
import { GetUserRequest } from "./example";
import type * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service UserService
 */
export interface IUserService extends grpc.UntypedServiceImplementation {
    /**
     * @generated from protobuf rpc: GetUser(GetUserRequest) returns (User);
     */
    getUser: grpc.handleUnaryCall<GetUserRequest, User>;
    /**
     * @generated from protobuf rpc: Createuser(CreateUserRequest) returns (CreateUserResponse);
     */
    createuser: grpc.handleUnaryCall<CreateUserRequest, CreateUserResponse>;
    /**
     * @generated from protobuf rpc: GetUserAddress(GetUserAddressRequest) returns (Address);
     */
    getUserAddress: grpc.handleUnaryCall<GetUserAddressRequest, Address>;
}
/**
 * @grpc/grpc-js definition for the protobuf service UserService.
 *
 * Usage: Implement the interface IUserService and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: IUserService = ...
 * server.addService(userServiceDefinition, service);
 * ```
 */
export const userServiceDefinition: grpc.ServiceDefinition<IUserService> = {
    getUser: {
        path: "/UserService/GetUser",
        originalName: "GetUser",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => User.fromBinary(bytes),
        requestDeserialize: bytes => GetUserRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(User.toBinary(value)),
        requestSerialize: value => Buffer.from(GetUserRequest.toBinary(value))
    },
    createuser: {
        path: "/UserService/Createuser",
        originalName: "Createuser",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => CreateUserResponse.fromBinary(bytes),
        requestDeserialize: bytes => CreateUserRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(CreateUserResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(CreateUserRequest.toBinary(value))
    },
    getUserAddress: {
        path: "/UserService/GetUserAddress",
        originalName: "GetUserAddress",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => Address.fromBinary(bytes),
        requestDeserialize: bytes => GetUserAddressRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(Address.toBinary(value)),
        requestSerialize: value => Buffer.from(GetUserAddressRequest.toBinary(value))
    }
};
