// @generated by protobuf-ts 2.9.0 with parameter server_grpc1
// @generated from protobuf file "example.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserService } from "./example";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { User } from "./example";
import type { GetUserRequest } from "./example";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service UserService
 */
export interface IUserServiceClient {
    /**
     * @generated from protobuf rpc: GetUser(GetUserRequest) returns (User);
     */
    getUser(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, User>;
}
/**
 * @generated from protobuf service UserService
 */
export class UserServiceClient implements IUserServiceClient, ServiceInfo {
    typeName = UserService.typeName;
    methods = UserService.methods;
    options = UserService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetUser(GetUserRequest) returns (User);
     */
    getUser(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, User> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserRequest, User>("unary", this._transport, method, opt, input);
    }
}
